[tools]
bun = "latest"
gitleaks = "latest"
helm = "latest"
jq = "latest"
ksops = "latest"
kubectl = "latest"
kustomize = "latest"
nsc = "latest"
opentofu = "latest"
shellcheck = "0.11.0"
sops = "latest"
step = "latest"
yq = "latest"
