apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wasmcloud-operator
  name: wasmcloud-operator
spec:
  selector:
    matchLabels:
      app: wasmcloud-operator
  template:
    metadata:
      labels:
        app: wasmcloud-operator
    spec:
      serviceAccountName: wasmcloud-operator
      containers:
        - image: ghcr.io/casualjim/wasmcloud-operator:existing-configmap
          imagePullPolicy: Always
          name: wasmcloud-operator
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          env:
            - name: RUST_LOG
              value: info
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # Ensure the operator trusts the internal platform CA when dialing NATS/wadm over TLS
            - name: WADM_NATS_TLS_CA_FILE
              value: /etc/ssl/platform-ca/ca.pem
            - name: SSL_CERT_FILE
              value: /etc/ssl/platform-ca/ca.pem
            # Point operator to the in-cluster NATS with TLS and supply creds to talk to wadm API
            - name: WADM_NATS_SERVER
              value: tls://nats.platform.svc:4222
            - name: WADM_NATS_CREDS_FILE
              value: /etc/nats-creds/wadm/wadm.creds
            - name: WADM_JETSTREAM_DOMAIN
              value: default
          volumeMounts:
            - name: platform-ca
              mountPath: /etc/ssl/platform-ca
              readOnly: true
            - name: nats-wadm-creds
              mountPath: /etc/nats-creds/wadm
              readOnly: true
      volumes:
        - name: platform-ca
          secret:
            secretName: step-root-ca-pem
            items:
              - key: ca.pem
                path: ca.pem
        - name: nats-wadm-creds
          secret:
            secretName: nats-wadm-creds
            items:
              - key: wadm.creds
                path: wadm.creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wasmcloud-operator
  labels:
    app: wasmcloud-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wasmcloud-operator
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
      - configmaps
      - serviceaccounts
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - k8s.wasmcloud.dev
    resources:
      - wasmcloudhostconfigs
      - wasmcloudhostconfigs/status
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wasmcloud-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wasmcloud-operator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: wasmcloud-operator
    namespace: platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wasmcloud-operator-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: wasmcloud-operator
    namespace: platform
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wasmcloud-operator
  name: wasmcloud-operator
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app: wasmcloud-operator
  type: ClusterIP
