apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/ingress
  - ingress-upstream-mtls.yaml

generators:
  - secrets-generator.yaml

labels:
  - pairs:
      env: dev
