apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/observability

generators:
  - secrets-generator.yaml

labels:
  - pairs:
      env: dev

helmCharts:
  - name: k8s-infra
    repo: https://charts.signoz.io
    releaseName: signoz-k8s-infra
    version: 0.14.1
    namespace: observability
    valuesInline:
      global:
        cloud: others
        clusterName: slipstream-dev
        deploymentEnvironment: dev
      otelCollectorEndpoint: ingest.us.signoz.cloud:443
      otelInsecure: false
      presets:
        otlpExporter:
          enabled: true
        debugExporter:
          enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      apiKeyExistingSecretName: signoz-api-key
      apiKeyExistingSecretKey: apiKey
