apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hello-world
  annotations:
    description: "HTTP hello world demo (wadm)"
spec:
  components:
    - name: http-component
      type: component
      properties:
        # Published example component image
        # Ref: https://github.com/wasmCloud/wadm/blob/main/oam/hello.yaml
        image: ghcr.io/wasmcloud/components/http-hello-world-rust:0.1.0
      traits:
        - type: spreadscaler
          properties:
            instances: 1
    - name: httpserver
      type: capability
      properties:
        # Official http server capability provider
        image: ghcr.io/wasmcloud/http-server:0.22.0
      traits:
        - type: link
          properties:
            target: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: default-http
                  properties:
                    # The provider will listen on this address inside the wasmCloud host pod
                    ADDRESS: 127.0.0.1:8080

# Usage:
# 1) Ensure wasmCloud host and wadm are running in your cluster (platform overlay installs both).
# 2) Deploy with wash (wadm):
#    wash app deploy k8s/verification/wadm-hello.yaml
# 3) To reach it, port-forward to a wasmCloud host pod and curl:
#    kubectl -n platform port-forward <wasmcloud-host-pod> 8080:8080
#    curl http://localhost:8080
