apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    token: ENC[AES256_GCM,data:nqh2MSGMxwhvQtye28vHgUrI35wqa5ZdAT08VDFRH12X0QXViihwXg==,iv:wwsLdhSTk7ARmwZKMcoA3nzFkqPqVWmOoj7Qo5EDm/w=,tag:SV4HWBW/ebNLKQqcC8qZJQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:880087769380:key/55535a25-24ba-401a-9194-06bf446862d8
          created_at: "2025-08-11T22:40:15Z"
          enc: AQICAHjRcKNsvMMo3eengKwHXr11uHUOJURd2hmGOYkhaWgSygF+OgfbCSS2X2y5Vts2ltd+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMyT+aefUyTwu9Y47GAgEQgDt+OGlW78rSytjwiwZhMFTQVfri4hOgL6lIxGjA9SmYSF6TNRip2S5VGnJxHKJAIx5XMTk6jHUBci3+zQ==
          aws_profile: ""
    lastmodified: "2025-08-11T22:40:15Z"
    mac: ENC[AES256_GCM,data:OyjaYp30g/sJLucMNOKsq9wcy2GPVsFautxdN3smSdLxjy8hlRWILzroT2s52ajnO2gE8seXIyKRqUVbJ2wQUaCydxMVIEMTApwRvlCAcIpt8Zrg2SUwTsm6yXHSqaikpXGTLvaNB514cXFWnJH4t/UivQMOCeT5WbcDYlloKP8=,iv:tQDSGe23loD5AnrdBXXDq4tJt2+8pBVmD5GmWcfKMaQ=,tag:9YOlcNWttMEpldAgHKF46Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
