apiVersion: v1
kind: ServiceAccount
metadata:
  name: vultr-ccm
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:vultr-ccm
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/status
      - services
      - endpoints
      - events
      - pods
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:vultr-ccm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:vultr-ccm
subjects:
  - kind: ServiceAccount
    name: vultr-ccm
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vultr-cloud-controller-manager
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: vultr-cloud-controller-manager
  template:
    metadata:
      labels:
        app: vultr-cloud-controller-manager
    spec:
      tolerations:
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          value: "true"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          effect: NoSchedule
        - key: "node-role.kubernetes.io/master"
          effect: NoSchedule
      serviceAccountName: vultr-ccm
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
        - name: vultr-cloud-controller-manager
          image: ghcr.io/vultr/vultr-cloud-controller-manager:v1.28.0
          args:
            - --cloud-provider=vultr
            - --leader-elect=true
            - --v=2
          env:
            - name: VULTR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: vultr-ccm
                  key: VULTR_API_KEY
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
---
