apiVersion: v1
kind: Secret
metadata:
    name: vultr-ccm
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:bPWox4LixRC+8u0=,iv:bhLQFhDcmyHdNkFFVT6x53m/pAX7t5kf3Qyu+M+LuSc=,tag:hbOP0m/AlcoX8Ivbiz4VzQ==,type:str]
    VULTR_API_KEY: ENC[AES256_GCM,data:QnMr+KAiaijNcw4=,iv:JOmnvnzRZiskeSlZxil01EGTD/bGnDzTv54lOIgv9hU=,tag:N7xy7UTDq7062HaMKqERzg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:880087769380:key/55535a25-24ba-401a-9194-06bf446862d8
          created_at: "2025-08-11T20:28:40Z"
          enc: AQICAHjRcKNsvMMo3eengKwHXr11uHUOJURd2hmGOYkhaWgSygHqAzIwcBMKiNZn2TX4MsHNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbAXkxpLQVldJ2Dt6AgEQgDv/2IGBYorS5CYk2BkFo5Aab4UPUlosZtU9geqXNHftgmDNgCJyEn2nu3Jc5RhmZHOmZzfnF68qCFlL+w==
          aws_profile: ""
    lastmodified: "2025-08-11T20:28:40Z"
    mac: ENC[AES256_GCM,data:V/Gb9O5cmOc3YMFSNHuwD6JogzmR9lpp4oDV1NbZjqIs0EnOgTMOikD3q2YIjVCjiofFWgJOR4M6Ax9yN8YmssK8Fc6GSMs6nMDyCXk9JrcqY0czNJ5pMEpFDDpuC0jDm9kiUP1mQOvN+P6jdwG0KrYUjbgdkMRnWPwvqAjOqN0=,iv:Ofgmeet5WDst59faYGj2gmxSSGNUIzwgJc0z1kYIxQY=,tag:gBt0T6kvjrqmHhqqx21aeg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2

