apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vultr-block-storage-wffc
provisioner: block.csi.vultr.com
parameters:
  block_type: high_perf
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

